### ISSUE TITLE
Support for Chef

### ISSUE THREAD

**Issue by bdemetris** [airbnb/gosal#24]
chef ohia run is pretty much the same as a puppet facter run.

**Comment by clburlison** [comment]
I’ll implement this once groob has his PRs merged. Then I won’t have to deal with merge conflicts.

**Comment by bdemetris** [comment]
i was having a think about this and it seems all config management output is json that we can throw  into a `map[string]interface{}` which is how puppet it now.  it stands to reason that we could convert `facter.go` to like `cfgmgmnt.go` and they all would simply take a `path` and a `command` from the config file.

im trying to think of reasons/use cases where we would want specific support for each tool.  i really cant think of any though.

**Comment by grahamgilbert** [comment]
That’s assuming all tools produce the same output. If the options are hard coded, support gets a lot easier.

**Comment by clburlison** [comment]
Well I've been working on this for the past few hours.... and ohai is dumb (yes you're aware). They have this great feature where in they like to dump `null` values. I'm having a hell of a time stripping those values. 

I've also poked @weswhet regarding Salt on slack and they have a different implementation in that they store all their keys under "local"

```json
{
    "local": {
        "kernel": "Darwin",
        "domain": "local",
...
}
```

While I absolutely agree about your idea to rename factor since you implemented the `path` and `command` options in the config lets leave it be for now. 😄 

Once Chef's Ohai is working we will have more information on if it makes more sense to split this or combine.
